---
tags: ,help-wanted
title: "[BUG-REPORT] Vaex `to_dask_array` fails `AttributeError: 'ValueError' object has no attribute 'numpy'`"
html_url: "https://github.com/vaexio/vaex/issues/1970"
user: Ben-Epstein
repo: vaexio/vaex
---

Thank you for reaching out and helping us improve Vaex!

Before you submit a new Issue, please read through the [documentation](https://docs.vaex.io/en/latest/). Also, make sure you search through the Open and Closed Issues - your problem may already be discussed or addressed.

**Description**
Please provide a clear and concise description of the problem. This should contain all the steps needed to reproduce the problem. A minimal code example that exposes the problem is very appreciated.

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`: {'vaex-core': '4.8.0', 'vaex-hdf5': '0.11.1'}
 - Vaex was installed via: pip / conda-forge / from source  pip
 - OS: MacOS

**Additional information**
Please state any supplementary information or provide additional context for the problem (e.g. screenshots, data, etc..).

```
import vaex

def tolist(x,y):
    return list([x,y])

data = {'A':[1,2,1],'B':['a','b','c'], 'C':['d', 'e', 'f']}
df = vaex.from_dict(data)
df.to_dask_array()
```
