---
tags: 
title: "UnboundLocalError when `mesolve` is used with callable `e_ops`"
html_url: "https://github.com/qutip/qutip/issues/2118"
user: balopat
repo: qutip/qutip
---

### Bug Description

`UnboundLocalError: local variable 'rho_t' referenced before assignment` is thrown when `mesolve` is used with callable `e_ops`. Note, it seems to be fixed on the 5.x branch (using `pip install --pre qutip`).

### Code to Reproduce the Bug

```shell
from qutip import * 
import numpy as np

s_00 = tensor(basis(2,0), basis(2,0))
P_00 = s_00 * s_00.dag()
e_ops = [ 
    lambda t, state: (state.ptrace([0,1]) * P_00).tr()   
    ]

tlist = np.linspace(0, 2*np.pi, 50)
res = mesolve(tensor(identity(2), identity(2), identity(3)),
              tensor(P_00, thermal_dm(3,0.1)), 
              tlist, 
              [],
              e_ops)
```


### Code Output

```shell
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-1-49ed87444849> in <module>
      9 
     10 tlist = np.linspace(0, 2*np.pi, 50)
---> 11 res = mesolve(tensor(identity(2), identity(2), identity(3)),
     12               tensor(P_00, thermal_dm(3,0.1)),
     13               tlist,

1 frames
/usr/local/lib/python3.9/dist-packages/qutip/mesolve.py in mesolve(H, rho0, tlist, c_ops, e_ops, args, options, progress_bar, _safe_mode)
    242         func(0., v, *ode_args) + v
    243 
--> 244     res = _generic_ode_solve(func, ode_args, rho0, tlist, e_ops, options,
    245                              progress_bar, dims=rho0.dims)
    246     res.num_collapse = len(c_ops)

/usr/local/lib/python3.9/dist-packages/qutip/mesolve.py in _generic_ode_solve(func, ode_args, rho0, tlist, e_ops, opt, progress_bar, dims)
    517         for m in range(n_expt_op):
    518             if not isinstance(e_ops[m], Qobj) and callable(e_ops[m]):
--> 519                 output.expect[m][t_idx] = e_ops[m](t, rho_t)
    520                 continue
    521             output.expect[m][t_idx] = expect_rho_vec(e_ops_data[m], r.y,

UnboundLocalError: local variable 'rho_t' referenced before assignment
```


### Expected Behaviour

no error.

### Your Environment

```shell
QuTiP Version:      4.7.1
Numpy Version:      1.22.4
Scipy Version:      1.10.1
Cython Version:     0.29.33
Matplotlib Version: 3.5.3
Python Version:     3.9.16
Number of CPUs:     2
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Linux (x86_64)
Installation path:  /usr/local/lib/python3.9/dist-packages/qutip
```


### Additional Context

_No response_